#!/usr/bin/env bash
# shellcheck shell=bash

sudo pacman -Sc
sudo pacman -Rns "$(pacman -Qtdq)"
#rmlint /home/alex
#echo `To execute rmlint script use "sh -c rmlint.sh"`
duf
sudo dust
sudo journalctl --vacuum-size=50M
