#!/usr/bin/env bash
# shellcheck shell=bash

# Setup multi-head displays for hostname: archbtw

xrandr --output DP-0 --primary --mode 1920x1080 --rate 144.00 --output DP-4 --mode 1920x1080 --rate 144.00 --left-of DP-0
